apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: taskmanager
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 32488
