//! SeaORM Entity. Generated by sea-orm-codegen 0.4.2

pub use super::projects::Entity as Projects;
pub use super::tag_task::Entity as TagTask;
pub use super::tags::Entity as Tags;
pub use super::tasks::Entity as Tasks;
